fixed error propagation

diff --git a/.github/workflows/flow1.yml b/.github/workflows/flow1.yml
--- a/.github/workflows/flow1.yml
+++ b/.github/workflows/flow1.yml
@@ -57,4 +57,10 @@ jobs:
 
       - name: Run reading dumped file
         run: |
-          go test -v read/read_test.go
+          set -o pipefail
+          go test -v read/read_test.go 2>&1 | tee output1.txt
+          test_status=${PIPESTATUS[0]}
+          if [ $test_status -ne 0 ]; then
+            echo "Tests failed"
+            exit $test_status
+          fi
