negative 3

diff --git a/.github/workflows/flow1.yml b/.github/workflows/flow1.yml
--- a/.github/workflows/flow1.yml
+++ b/.github/workflows/flow1.yml
@@ -62,7 +62,9 @@ jobs:
       - name: Run reading dumped file
         run: |
           go test -v read/read_test.go 2>&1 | tee output1.txt
-          if [  ${PIPESTATUS[0]} -ne 0   ]; then
-            echo "Test failed"
-          exit 1
+          test_status=${PIPESTATUS[0]}
+          if [ $test_status -ne 0 ]; then
+            echo "Tests failed"
+            exit $test_status
           fi
+
